name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: npm ci

      - run: npm run typecheck

      - run: npm run build

      - run: npm run check:ci

      - run: npm run test:cov

      # build container when triggered by release (push on tag)
      - name: Log in to the GitHub container registry
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker setup - QEMU
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: docker/setup-qemu-action@v3

      - name: Docker setup - Buildx
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: docker/metadata-action@v5
        id: meta
        with:
            images: |
                ghcr.io/nerivec/zigbee2mqtt-windfront
            tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}

      - name: Docker build and push
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
            context: .
            file: Dockerfile
            platforms: linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/riscv64,linux/386
            tags: ${{ steps.meta.outputs.tags }}
            push: true
            build-args: |
                VERSION=${{ github.ref_name }}
                DATE=${{ github.event.repository.updated_at }}

      - name: Add tarball dist to release assets
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        run: |
          mv dist zigbee2mqtt-windfront-${{ github.ref_name }}
          tar -czvf zigbee2mqtt-windfront-${{ github.ref_name }}.tar.gz zigbee2mqtt-windfront-${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} zigbee2mqtt-windfront-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
