name: Update i18n EN translations

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: npm ci

      - run: npm i -D zigbee-herdsman-converters

      - run: node ./scripts/override-z2m-en.mjs

      - run: npm run check

      - name: Commit changes
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add ./src/i18n/locales/en.json
            git commit -m "Update i18n EN translations" -m "cc: @Nerivec @Nicooow (fr) @domotick (fr)" || echo 'Nothing to commit'
            git push
